### ISSUE TITLE
Please use gopkg.in/gorp.v1

### ISSUE THREAD

**Issue by GeertJohan** [Xe/clop.science#3]
I see that you are importing `gorp` from `github.com/go-gorp/gorp`.
This is the unstable "bleeding edge" version. We are working on breaking changes, it is likely that your program will fail to compile unless you update your code to reflect the changes.

Please use `gopkg.in/gorp.v1` as import path, it provides the last stable gorp v1 release and will not break (unless a breaking change is required to fix a security issue).

When the changes to the master branch are complete, v2 will be released. See go-gorp/gorp#270 for more information.
Thanks.

**Comment by Xe** [comment]
Thanks for the heads-up, but I'm using [godep](https://github.com/Xe/clop.science/tree/master/Godeps/_workspace/src/github.com/go-gorp/gorp). I will keep this in mind if/when I update this code tree in the future. I haven't had a reason to lately as everything has been working well enough that there is no need.

**Comment by GeertJohan** [comment]
Ah okay. I guess it came still up on godoc's 'imported by' page because the import path isn't rewritten to `github.com/Xe/clop.science/Godep/_workspace/github.com/go-gorp/gorp`. You might consider doing that so the code will compile correctly with simply `go build`.

Anyway, good to hear you're covered! Make sure to check gorp for v2, it's going to become even more awesome :smile:

**Comment by Xe** [comment]
Yeah, I know. I find the current state of everything to just be awful, so I used the solution that (at the time) was least abysmal. Still, thank you so much for going out of your way to let people know about deprecation!
